### ISSUE TITLE
提交后input失去焦点

### ISSUE THREAD

**Issue by boruHan2526** [Megusuri56/walkingwords#1]
在默写模式下，每次提交后就会失去焦点，这有点烦不是么🤷‍

**Comment by Megusuri56** [comment]
~~没想到真的有人在用太好了~~
已经改了，感谢支持

**Comment by boruHan2526** [comment]
> ~没想到真的有人在用太好了~ 已经改了，感谢支持

谢谢 :) 
希望一个月之后的N1能过 XD
