### ISSUE TITLE
默写模式下缺少检查（检查不起作用）

### ISSUE THREAD

**Issue by boruHan2526** [Megusuri56/walkingwords#2]
无论输入什么回车都能过，，，
加个CHECK比较好吧。。。

**Comment by Megusuri56** [comment]
已修复。
这个问题是因为在一个表单下只有一个文本框时，按下回车将会触发表单的提交事件，导致页面刷新。
这并不视为通过，页面下方的进度条也不会推进。请按下空格键提交，答案正确时可以看到进度条增长了。
祝考试顺利！
